local opt = vim.opt

opt.backup = false
opt.swapfile = false
opt.clipboard = "unnamedplus"
opt.number = true
opt.relativenumber = false
opt.showmode = false
opt.showtabline = 2
opt.expandtab = true
opt.tabstop = 2
opt.softtabstop = 2
opt.shiftwidth = 2
opt.smartindent = true
opt.ignorecase = true
opt.smartcase = true
opt.hlsearch = true
opt.conceallevel = 0
opt.cursorline = true
opt.background = "dark"
opt.modeline = true
opt.modelines = 3
