[terminal]
vt = 1

[default_session]
command = "agreety --cmd /usr/local/bin/niri-session-wrapper"
user = "greeter"

[initial_session]
command = "/usr/local/bin/niri-session-wrapper"
user = "sanyaxo"
