local opt = vim.opt

opt.backup = false
opt.swapfile = false
opt.clipboard = "unnamedplus"
opt.number = true
opt.relativenumber = false
opt.showmode = false
opt.showtabline = 2
opt.expandtab = true
opt.tabstop = 4
opt.softtabstop= 4
opt.shiftwidth= 4
opt.smartindent = true
opt.ignorecase = true
opt.smartcase = true
opt.hlsearch = true
opt.conceallevel = 0
opt.cursorline = true --highlight current line
opt.background = "dark"
