--enable-features=UseOzonePlatform,WaylandWindowDecorations,AllowQt,VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,UseVulkanForWebGL,DefaultANGLEVulkan,VulkanFromANGLE
--ozone-platform=wayland
--password-store=gnome-libsecret
--gtk-version=4
--enable-unsafe-webgpu
