[env]
TERM="xterm-256color"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#ff7aba"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#ffd1db"
cyan = "#ffaad9"
white = "#a6adc8"

[colors.primary]
background = "#000000"
foreground = "#9f9fa1"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[bell]
command = "None"
duration = 0

[cursor]
blink_interval = 500
blink_timeout = 0
thickness = 0.15
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 8

[font.bold]
family = "Iosevka Term SS06"
style = "Bold Extended"

[font.bold_italic]
family = "Iosevka Term SS06"
style = "Bold Extended Italic"

[font.italic]
family = "Iosevka Term SS06"
style = "Light Italic"

[font.normal]
family = "Iosevka Term SS06"
style = "Light Extended"

[mouse]
hide_when_typing = false

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[general]
live_config_reload = true
ipc_socket = true
